name: Main Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != staging ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; 
          then
            echo "Error: Pull request must come from 'staging' or 'hotfix/' branch"
            exit 1
          fi